import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfólio de Josué Ocanha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta property="og:title" content="Josué Ocanha - Portfólio de Desenvolvedor" />
        <meta property="og:description" content="Portfólio de Josué Ocanha, desenvolvedor frontend e backend com experiência em tecnologias modernas como Node.js, React, TypeScript e mais." />
        <meta property="og:image" content="/public/pagina.png" />
        <meta property="og:url" content="https://example.com/pagina" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Portfólio de Josué Ocanha" />
        <meta property="og:locale" content="pt_BR" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
